// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjjunqakfipjrngqhdlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqanVucWFrZmlwanJuZ3FoZGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTk1ODEsImV4cCI6MjA2MjUzNTU4MX0._7wqKb8XAWgDZrVcDY4z8Sy__8HZRl_GMuMsKgM8qpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);